---
# - name: test
#   copy:
#     content: "your config line here"
#     dest: "/etc/asher.txt"
#   tags:
#     - test
# - name: Print the actual user
#   command: whoami
#   tags:
#     - test
#   register: out


# - debug:
#     var: out
# - name: Print the actual user
#   command: hostname
#   tags:
#     - test
#   register: hostout

# - debug:
#     var: hostout
# preform the commands on the switch