---

# - name: save data to excel file  
#   dict_to_excel:
#       column: 1
#       data: "{{host_name}}"
#       file_to_save: "{{excel_save_file}}"
#   #throttle: 1

- name: save dict data to excel file from  
  dict_to_excel:
      dict_data: "{{device_facts_list}}"
      file_to_save: "{{excel_save_file}}"
  #throttle: 1 